
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import luban.AbstractBean;


public final class CommonConfig extends AbstractBean {
    public static final int __ID__ = -180055763;
    /**
     * key
     */
    public final String key;
    public final int intParam;
    /**
     * list&lt;int&gt;参数
     */
    public final java.util.ArrayList<Integer> intParams;
    /**
     * list&lt;string&gt;参数
     */
    public final java.util.ArrayList<String> strParams;
    /**
     * 描述
     */
    public final String desc;
    public CommonConfig(JsonObject _buf) {
        key = _buf.get("key").getAsString();
        intParam = _buf.get("intParam").getAsInt();
        {
            com.google.gson.JsonArray _json0_ = _buf.get("intParams").getAsJsonArray();
            intParams = new java.util.ArrayList<Integer>(_json0_.size());
            for (JsonElement _e0 : _json0_) {
                int _v0;
                _v0 = _e0.getAsInt();
                intParams.add(_v0);
            }
        }
        {
            com.google.gson.JsonArray _json0_ = _buf.get("strParams").getAsJsonArray();
            strParams = new java.util.ArrayList<String>(_json0_.size());
            for (JsonElement _e0 : _json0_) {
                String _v0;
                _v0 = _e0.getAsString();
                strParams.add(_v0);
            }
        }
        desc = _buf.get("desc").getAsString();
    }

    public static CommonConfig deserialize(JsonObject _buf) {
        return new CommonConfig(_buf);
    }

    @Override
    public int getTypeId() {
        return __ID__;
    }

    @Override
    public String toString() {
        return "{ "
                + "(format_field_name __code_style field.name):" + key + ","
                + "(format_field_name __code_style field.name):" + intParam + ","
                + "(format_field_name __code_style field.name):" + intParams + ","
                + "(format_field_name __code_style field.name):" + strParams + ","
                + "(format_field_name __code_style field.name):" + desc + ","
                + "}";
    }
}

