
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import luban.AbstractBean;


public final class Drop extends AbstractBean {
    public static final int __ID__ = 2138895;
    /**
     * 掉落id
     */
    public final int id;
    /**
     * 掉落名称
     */
    public final String name;
    /**
     * 掉落规则<br/>0.不随机，drops都掉落<br/>1.权重随机<br/>按照权重，随机number个发放<br/>2.随机group掉落
     */
    public final int dropRule;
    /**
     * 组数据<br/>dropRule=1或2生效<br/>先随机组，剔除非改组项，按照权重，随机number个发放
     */
    public final java.util.ArrayList<Integer> totalGroup;
    /**
     * 组权重<br/>totalGroup随机用的权重，长度对应
     */
    public final java.util.ArrayList<Integer> gWeight;
    /**
     * 掉落数量
     */
    public final int numbers;
    /**
     * <br/>同一个奖励是否重复随机
     */
    public final boolean repeatable;
    public final java.util.ArrayList<cfg.item.Drop> drops;
    public Drop(JsonObject _buf) {
        id = _buf.get("id").getAsInt();
        name = _buf.get("name").getAsString();
        dropRule = _buf.get("dropRule").getAsInt();
        {
            com.google.gson.JsonArray _json0_ = _buf.get("totalGroup").getAsJsonArray();
            totalGroup = new java.util.ArrayList<Integer>(_json0_.size());
            for (JsonElement _e0 : _json0_) {
                int _v0;
                _v0 = _e0.getAsInt();
                totalGroup.add(_v0);
            }
        }
        {
            com.google.gson.JsonArray _json0_ = _buf.get("gWeight").getAsJsonArray();
            gWeight = new java.util.ArrayList<Integer>(_json0_.size());
            for (JsonElement _e0 : _json0_) {
                int _v0;
                _v0 = _e0.getAsInt();
                gWeight.add(_v0);
            }
        }
        numbers = _buf.get("numbers").getAsInt();
        repeatable = _buf.get("repeatable").getAsBoolean();
        {
            com.google.gson.JsonArray _json0_ = _buf.get("drops").getAsJsonArray();
            drops = new java.util.ArrayList<cfg.item.Drop>(_json0_.size());
            for (JsonElement _e0 : _json0_) {
                cfg.item.Drop _v0;
                _v0 = cfg.item.Drop.deserialize(_e0.getAsJsonObject());
                drops.add(_v0);
            }
        }
    }

    public static Drop deserialize(JsonObject _buf) {
        return new Drop(_buf);
    }

    @Override
    public int getTypeId() {
        return __ID__;
    }

    @Override
    public String toString() {
        return "{ "
                + "(format_field_name __code_style field.name):" + id + ","
                + "(format_field_name __code_style field.name):" + name + ","
                + "(format_field_name __code_style field.name):" + dropRule + ","
                + "(format_field_name __code_style field.name):" + totalGroup + ","
                + "(format_field_name __code_style field.name):" + gWeight + ","
                + "(format_field_name __code_style field.name):" + numbers + ","
                + "(format_field_name __code_style field.name):" + repeatable + ","
                + "(format_field_name __code_style field.name):" + drops + ","
                + "}";
    }
}

