
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import luban.AbstractBean;


public final class Fish extends AbstractBean {
    public static final int __ID__ = 2189944;
    /**
     * 这是id
     */
    public final int id;
    /**
     * 鱼的分类
     */
    public final int type;
    /**
     * 不显示
     */
    public final int hide;
    /**
     * 玩家等级
     */
    public final int level;
    /**
     * 货币ID
     */
    public final int tokenId;
    /**
     * 购买价格(对应等级)
     */
    public final java.util.ArrayList<Integer> cost;
    /**
     * 模型
     */
    public final String model;
    /**
     * 移动速度
     */
    public final float speed;
    /**
     * 缩放
     */
    public final float Scale;
    /**
     * 名字
     */
    public final String name;
    public Fish(JsonObject _buf) {
        id = _buf.get("id").getAsInt();
        type = _buf.get("type").getAsInt();
        hide = _buf.get("hide").getAsInt();
        level = _buf.get("level").getAsInt();
        tokenId = _buf.get("tokenId").getAsInt();
        {
            com.google.gson.JsonArray _json0_ = _buf.get("cost").getAsJsonArray();
            cost = new java.util.ArrayList<Integer>(_json0_.size());
            for (JsonElement _e0 : _json0_) {
                int _v0;
                _v0 = _e0.getAsInt();
                cost.add(_v0);
            }
        }
        model = _buf.get("model").getAsString();
        speed = _buf.get("speed").getAsFloat();
        Scale = _buf.get("Scale").getAsFloat();
        name = _buf.get("name").getAsString();
    }

    public static Fish deserialize(JsonObject _buf) {
        return new Fish(_buf);
    }

    @Override
    public int getTypeId() {
        return __ID__;
    }

    @Override
    public String toString() {
        return "{ "
                + "(format_field_name __code_style field.name):" + id + ","
                + "(format_field_name __code_style field.name):" + type + ","
                + "(format_field_name __code_style field.name):" + hide + ","
                + "(format_field_name __code_style field.name):" + level + ","
                + "(format_field_name __code_style field.name):" + tokenId + ","
                + "(format_field_name __code_style field.name):" + cost + ","
                + "(format_field_name __code_style field.name):" + model + ","
                + "(format_field_name __code_style field.name):" + speed + ","
                + "(format_field_name __code_style field.name):" + Scale + ","
                + "(format_field_name __code_style field.name):" + name + ","
                + "}";
    }
}

