
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

import com.google.gson.JsonObject;
import luban.AbstractBean;


public final class Level extends AbstractBean {
    public static final int __ID__ = 73313124;
    /**
     * 这是id
     */
    public final int id;
    /**
     * 等级
     */
    public final int lv;
    /**
     * 总经验
     */
    public final int totalExp;
    /**
     * 每级所需经验
     */
    public final int levelExp;
    public Level(JsonObject _buf) {
        id = _buf.get("id").getAsInt();
        lv = _buf.get("lv").getAsInt();
        totalExp = _buf.get("totalExp").getAsInt();
        levelExp = _buf.get("levelExp").getAsInt();
    }

    public static Level deserialize(JsonObject _buf) {
        return new Level(_buf);
    }

    @Override
    public int getTypeId() {
        return __ID__;
    }

    @Override
    public String toString() {
        return "{ "
                + "(format_field_name __code_style field.name):" + id + ","
                + "(format_field_name __code_style field.name):" + lv + ","
                + "(format_field_name __code_style field.name):" + totalExp + ","
                + "(format_field_name __code_style field.name):" + levelExp + ","
                + "}";
    }
}

