
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

import com.google.gson.JsonObject;
import luban.AbstractBean;


public final class RewardItem extends AbstractBean {
    public static final int __ID__ = -610604286;
    /**
     * 奖励id
     */
    public final int id;
    /**
     * 名称
     */
    public final String name;
    /**
     * 类型
     */
    public final int type;
    /**
     * 鱼ID
     */
    public final int fishId;
    /**
     * 积分
     */
    public final int integral;
    public RewardItem(JsonObject _buf) {
        id = _buf.get("id").getAsInt();
        name = _buf.get("name").getAsString();
        type = _buf.get("type").getAsInt();
        fishId = _buf.get("fishId").getAsInt();
        integral = _buf.get("integral").getAsInt();
    }

    public static RewardItem deserialize(JsonObject _buf) {
        return new RewardItem(_buf);
    }

    @Override
    public int getTypeId() {
        return __ID__;
    }

    @Override
    public String toString() {
        return "{ "
                + "(format_field_name __code_style field.name):" + id + ","
                + "(format_field_name __code_style field.name):" + name + ","
                + "(format_field_name __code_style field.name):" + type + ","
                + "(format_field_name __code_style field.name):" + fishId + ","
                + "(format_field_name __code_style field.name):" + integral + ","
                + "}";
    }
}

