
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

import com.google.gson.JsonObject;
import com.think.luban.anno.CfgTable;
import luban.AbstractBean;

@CfgTable("tbrewards")
public final class Rewards extends AbstractBean {
    public static final int __ID__ = -1529663740;
    /**
     * 这是id
     */
    public final int id;
    /**
     * 0全平台<br/>1微信<br/>2抖音
     */
    public final int plamform;
    public final String key;
    /**
     * 名字
     */
    public final String name;
    /**
     * 领取次数
     */
    public final int times;
    /**
     * 0生命周期唯一<br/>1每日
     */
    public final int type;
    /**
     * 掉落表ID
     */
    public final int dropId;
    public Rewards(JsonObject _buf) {
        id = _buf.get("id").getAsInt();
        plamform = _buf.get("plamform").getAsInt();
        key = _buf.get("key").getAsString();
        name = _buf.get("name").getAsString();
        times = _buf.get("times").getAsInt();
        type = _buf.get("type").getAsInt();
        dropId = _buf.get("dropId").getAsInt();
    }

    public static Rewards deserialize(JsonObject _buf) {
        return new Rewards(_buf);
    }

    @Override
    public int getTypeId() {
        return __ID__;
    }

    @Override
    public String toString() {
        return "{ "
                + "(format_field_name __code_style field.name):" + id + ","
                + "(format_field_name __code_style field.name):" + plamform + ","
                + "(format_field_name __code_style field.name):" + key + ","
                + "(format_field_name __code_style field.name):" + name + ","
                + "(format_field_name __code_style field.name):" + times + ","
                + "(format_field_name __code_style field.name):" + type + ","
                + "(format_field_name __code_style field.name):" + dropId + ","
                + "}";
    }
}

