
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import luban.AbstractBean;


public final class RewardGroup extends AbstractBean {
    public static final int __ID__ = -1750760336;
    /**
     * id
     */
    public final int id;
    /**
     * 名称
     */
    public final String name;
    /**
     * 循环周期类型
     */
    public final int type;
    /**
     * 奖励组类型
     */
    public final int kind;
    /**
     * 周期值
     */
    public final String cycle;
    /**
     * 所属游戏ID
     */
    public final java.util.ArrayList<Integer> gameIds;
    /**
     * 奖励ID列表
     */
    public final java.util.ArrayList<Integer> rewards;
    public RewardGroup(JsonObject _buf) {
        id = _buf.get("id").getAsInt();
        name = _buf.get("name").getAsString();
        type = _buf.get("type").getAsInt();
        kind = _buf.get("kind").getAsInt();
        cycle = _buf.get("cycle").getAsString();
        {
            com.google.gson.JsonArray _json0_ = _buf.get("gameIds").getAsJsonArray();
            gameIds = new java.util.ArrayList<Integer>(_json0_.size());
            for (JsonElement _e0 : _json0_) {
                int _v0;
                _v0 = _e0.getAsInt();
                gameIds.add(_v0);
            }
        }
        {
            com.google.gson.JsonArray _json0_ = _buf.get("rewards").getAsJsonArray();
            rewards = new java.util.ArrayList<Integer>(_json0_.size());
            for (JsonElement _e0 : _json0_) {
                int _v0;
                _v0 = _e0.getAsInt();
                rewards.add(_v0);
            }
        }
    }

    public static RewardGroup deserialize(JsonObject _buf) {
        return new RewardGroup(_buf);
    }

    @Override
    public int getTypeId() {
        return __ID__;
    }

    @Override
    public String toString() {
        return "{ "
                + "(format_field_name __code_style field.name):" + id + ","
                + "(format_field_name __code_style field.name):" + name + ","
                + "(format_field_name __code_style field.name):" + type + ","
                + "(format_field_name __code_style field.name):" + kind + ","
                + "(format_field_name __code_style field.name):" + cycle + ","
                + "(format_field_name __code_style field.name):" + gameIds + ","
                + "(format_field_name __code_style field.name):" + rewards + ","
                + "}";
    }
}

