
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import luban.AbstractBean;


public final class Shop extends AbstractBean {
    public static final int __ID__ = 2576150;
    /**
     * 这是id
     */
    public final int id;
    /**
     * 名字
     */
    public final String name;
    /**
     * 过审屏蔽
     */
    public final boolean approval;
    /**
     * 页签
     */
    public final int tab;
    /**
     * 掉落
     */
    public final int dropId;
    /**
     * 数据来自服务器
     */
    public final int serverInit;
    /**
     * 购买限制类型<br/>0.无限制<br/>1.每日限购次数<br/>2.每周限购（周一重置）<br/>3.每月限购（1号重置）<br/>4.总限购（整个游戏生命周期购买次数）
     */
    public final int limitType;
    /**
     * 购买次数限制<br/>（与limitType配合）<br/>原dayLimit
     */
    public final int limitNum;
    /**
     * 价格模式<br/>-1 表示看广告<br/>1. 固定价格<br/>2. 阶梯价格<br/>3.固定价格+广告免费<br/>4.阶梯价格+广告免费
     */
    public final int priceType;
    /**
     * 货币ID<br/>原money
     */
    public final int tokenId;
    /**
     * 金币消耗<br/>原goldCost
     */
    public final int price;
    /**
     * 价格阶梯<br/>price + price * priceSteps[buyTimes]
     */
    public final java.util.ArrayList<Integer> priceSteps;
    /**
     * 解锁条件<br/>1.玩家等级<br/>2.关卡进度
     */
    public final int condition;
    /**
     * 解锁条件值<br/>
     */
    public final int conditionValue;
    public Shop(JsonObject _buf) {
        id = _buf.get("id").getAsInt();
        name = _buf.get("name").getAsString();
        approval = _buf.get("approval").getAsBoolean();
        tab = _buf.get("tab").getAsInt();
        dropId = _buf.get("dropId").getAsInt();
        serverInit = _buf.get("serverInit").getAsInt();
        limitType = _buf.get("limitType").getAsInt();
        limitNum = _buf.get("limitNum").getAsInt();
        priceType = _buf.get("priceType").getAsInt();
        tokenId = _buf.get("tokenId").getAsInt();
        price = _buf.get("price").getAsInt();
        {
            com.google.gson.JsonArray _json0_ = _buf.get("priceSteps").getAsJsonArray();
            priceSteps = new java.util.ArrayList<Integer>(_json0_.size());
            for (JsonElement _e0 : _json0_) {
                int _v0;
                _v0 = _e0.getAsInt();
                priceSteps.add(_v0);
            }
        }
        condition = _buf.get("condition").getAsInt();
        conditionValue = _buf.get("conditionValue").getAsInt();
    }

    public static Shop deserialize(JsonObject _buf) {
        return new Shop(_buf);
    }

    @Override
    public int getTypeId() {
        return __ID__;
    }

    @Override
    public String toString() {
        return "{ "
                + "(format_field_name __code_style field.name):" + id + ","
                + "(format_field_name __code_style field.name):" + name + ","
                + "(format_field_name __code_style field.name):" + approval + ","
                + "(format_field_name __code_style field.name):" + tab + ","
                + "(format_field_name __code_style field.name):" + dropId + ","
                + "(format_field_name __code_style field.name):" + serverInit + ","
                + "(format_field_name __code_style field.name):" + limitType + ","
                + "(format_field_name __code_style field.name):" + limitNum + ","
                + "(format_field_name __code_style field.name):" + priceType + ","
                + "(format_field_name __code_style field.name):" + tokenId + ","
                + "(format_field_name __code_style field.name):" + price + ","
                + "(format_field_name __code_style field.name):" + priceSteps + ","
                + "(format_field_name __code_style field.name):" + condition + ","
                + "(format_field_name __code_style field.name):" + conditionValue + ","
                + "}";
    }
}

