
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import luban.AbstractBean;


public final class Sign extends AbstractBean {
    public static final int __ID__ = 2576861;
    /**
     * 这是id
     */
    public final int id;
    /**
     * 0全平台<br/>1微信<br/>2抖音
     */
    public final int plamform;
    /**
     * 类型
     */
    public final int type;
    /**
     * 名字
     */
    public final String name;
    /**
     * 领取次数
     */
    public final int times;
    /**
     * 道具
     */
    public final java.util.ArrayList<Integer> items;
    /**
     * 数量
     */
    public final java.util.ArrayList<Integer> number;
    public Sign(JsonObject _buf) {
        id = _buf.get("id").getAsInt();
        plamform = _buf.get("plamform").getAsInt();
        type = _buf.get("type").getAsInt();
        name = _buf.get("name").getAsString();
        times = _buf.get("times").getAsInt();
        {
            com.google.gson.JsonArray _json0_ = _buf.get("items").getAsJsonArray();
            items = new java.util.ArrayList<Integer>(_json0_.size());
            for (JsonElement _e0 : _json0_) {
                int _v0;
                _v0 = _e0.getAsInt();
                items.add(_v0);
            }
        }
        {
            com.google.gson.JsonArray _json0_ = _buf.get("number").getAsJsonArray();
            number = new java.util.ArrayList<Integer>(_json0_.size());
            for (JsonElement _e0 : _json0_) {
                int _v0;
                _v0 = _e0.getAsInt();
                number.add(_v0);
            }
        }
    }

    public static Sign deserialize(JsonObject _buf) {
        return new Sign(_buf);
    }

    @Override
    public int getTypeId() {
        return __ID__;
    }

    @Override
    public String toString() {
        return "{ "
                + "(format_field_name __code_style field.name):" + id + ","
                + "(format_field_name __code_style field.name):" + plamform + ","
                + "(format_field_name __code_style field.name):" + type + ","
                + "(format_field_name __code_style field.name):" + name + ","
                + "(format_field_name __code_style field.name):" + times + ","
                + "(format_field_name __code_style field.name):" + items + ","
                + "(format_field_name __code_style field.name):" + number + ","
                + "}";
    }
}

