
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

import com.google.gson.JsonElement;


public final class TbCommonConfig {
    private final java.util.Map<String, CommonConfig> _dataMap;
    private final java.util.List<CommonConfig> _dataList;

    public TbCommonConfig(JsonElement _buf) {
        _dataMap = new java.util.HashMap<String, CommonConfig>();
        _dataList = new java.util.ArrayList<CommonConfig>();

        for (JsonElement _e_ : _buf.getAsJsonArray()) {
            CommonConfig _v;
            _v = CommonConfig.deserialize(_e_.getAsJsonObject());
            _dataList.add(_v);
            _dataMap.put(_v.key, _v);
        }
    }

    public java.util.Map<String, CommonConfig> getDataMap() {
        return _dataMap;
    }

    public java.util.List<CommonConfig> getDataList() {
        return _dataList;
    }

    public CommonConfig get(String key) {
        return _dataMap.get(key);
    }

}

