
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

import com.google.gson.JsonElement;


public final class TbDrop {
    private final java.util.Map<Integer, Drop> _dataMap;
    private final java.util.List<Drop> _dataList;

    public TbDrop(JsonElement _buf) {
        _dataMap = new java.util.HashMap<Integer, Drop>();
        _dataList = new java.util.ArrayList<Drop>();

        for (JsonElement _e_ : _buf.getAsJsonArray()) {
            Drop _v;
            _v = Drop.deserialize(_e_.getAsJsonObject());
            _dataList.add(_v);
            _dataMap.put(_v.id, _v);
        }
    }

    public java.util.Map<Integer, Drop> getDataMap() {
        return _dataMap;
    }

    public java.util.List<Drop> getDataList() {
        return _dataList;
    }

    public Drop get(int key) {
        return _dataMap.get(key);
    }

}

