
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

import com.google.gson.JsonElement;


public final class TbFish {
    private final java.util.Map<Integer, Fish> _dataMap;
    private final java.util.List<Fish> _dataList;

    public TbFish(JsonElement _buf) {
        _dataMap = new java.util.HashMap<Integer, Fish>();
        _dataList = new java.util.ArrayList<Fish>();

        for (JsonElement _e_ : _buf.getAsJsonArray()) {
            Fish _v;
            _v = Fish.deserialize(_e_.getAsJsonObject());
            _dataList.add(_v);
            _dataMap.put(_v.id, _v);
        }
    }

    public java.util.Map<Integer, Fish> getDataMap() {
        return _dataMap;
    }

    public java.util.List<Fish> getDataList() {
        return _dataList;
    }

    public Fish get(int key) {
        return _dataMap.get(key);
    }

}

