
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

import com.google.gson.JsonElement;


public final class TbGameLevel {
    private final java.util.Map<Integer, GameLevel> _dataMap;
    private final java.util.List<GameLevel> _dataList;

    public TbGameLevel(JsonElement _buf) {
        _dataMap = new java.util.HashMap<Integer, GameLevel>();
        _dataList = new java.util.ArrayList<GameLevel>();

        for (JsonElement _e_ : _buf.getAsJsonArray()) {
            GameLevel _v;
            _v = GameLevel.deserialize(_e_.getAsJsonObject());
            _dataList.add(_v);
            _dataMap.put(_v.id, _v);
        }
    }

    public java.util.Map<Integer, GameLevel> getDataMap() {
        return _dataMap;
    }

    public java.util.List<GameLevel> getDataList() {
        return _dataList;
    }

    public GameLevel get(int key) {
        return _dataMap.get(key);
    }

}

