
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

import com.google.gson.JsonElement;


public final class TbGuideCard {
    private final java.util.Map<Integer, GuideCard> _dataMap;
    private final java.util.List<GuideCard> _dataList;

    public TbGuideCard(JsonElement _buf) {
        _dataMap = new java.util.HashMap<Integer, GuideCard>();
        _dataList = new java.util.ArrayList<GuideCard>();

        for (JsonElement _e_ : _buf.getAsJsonArray()) {
            GuideCard _v;
            _v = GuideCard.deserialize(_e_.getAsJsonObject());
            _dataList.add(_v);
            _dataMap.put(_v.id, _v);
        }
    }

    public java.util.Map<Integer, GuideCard> getDataMap() {
        return _dataMap;
    }

    public java.util.List<GuideCard> getDataList() {
        return _dataList;
    }

    public GuideCard get(int key) {
        return _dataMap.get(key);
    }

}

