
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

import com.google.gson.JsonElement;


public final class TbItem {
    private final java.util.Map<Integer, Item> _dataMap;
    private final java.util.List<Item> _dataList;

    public TbItem(JsonElement _buf) {
        _dataMap = new java.util.HashMap<Integer, Item>();
        _dataList = new java.util.ArrayList<Item>();

        for (JsonElement _e_ : _buf.getAsJsonArray()) {
            Item _v;
            _v = Item.deserialize(_e_.getAsJsonObject());
            _dataList.add(_v);
            _dataMap.put(_v.id, _v);
        }
    }

    public java.util.Map<Integer, Item> getDataMap() {
        return _dataMap;
    }

    public java.util.List<Item> getDataList() {
        return _dataList;
    }

    public Item get(int key) {
        return _dataMap.get(key);
    }

}

