
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

import com.google.gson.JsonElement;


public final class TbLevel {
    private final java.util.Map<Integer, Level> _dataMap;
    private final java.util.List<Level> _dataList;

    public TbLevel(JsonElement _buf) {
        _dataMap = new java.util.HashMap<Integer, Level>();
        _dataList = new java.util.ArrayList<Level>();

        for (JsonElement _e_ : _buf.getAsJsonArray()) {
            Level _v;
            _v = Level.deserialize(_e_.getAsJsonObject());
            _dataList.add(_v);
            _dataMap.put(_v.id, _v);
        }
    }

    public java.util.Map<Integer, Level> getDataMap() {
        return _dataMap;
    }

    public java.util.List<Level> getDataList() {
        return _dataList;
    }

    public Level get(int key) {
        return _dataMap.get(key);
    }

}

