
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

import com.google.gson.JsonElement;


public final class TbRewardGroup {
    private final java.util.Map<Integer, RewardGroup> _dataMap;
    private final java.util.List<RewardGroup> _dataList;

    public TbRewardGroup(JsonElement _buf) {
        _dataMap = new java.util.HashMap<Integer, RewardGroup>();
        _dataList = new java.util.ArrayList<RewardGroup>();

        for (JsonElement _e_ : _buf.getAsJsonArray()) {
            RewardGroup _v;
            _v = RewardGroup.deserialize(_e_.getAsJsonObject());
            _dataList.add(_v);
            _dataMap.put(_v.id, _v);
        }
    }

    public java.util.Map<Integer, RewardGroup> getDataMap() {
        return _dataMap;
    }

    public java.util.List<RewardGroup> getDataList() {
        return _dataList;
    }

    public RewardGroup get(int key) {
        return _dataMap.get(key);
    }

}

