
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

import com.google.gson.JsonElement;


public final class TbRewardItem {
    private final java.util.Map<Integer, RewardItem> _dataMap;
    private final java.util.List<RewardItem> _dataList;

    public TbRewardItem(JsonElement _buf) {
        _dataMap = new java.util.HashMap<Integer, RewardItem>();
        _dataList = new java.util.ArrayList<RewardItem>();

        for (JsonElement _e_ : _buf.getAsJsonArray()) {
            RewardItem _v;
            _v = RewardItem.deserialize(_e_.getAsJsonObject());
            _dataList.add(_v);
            _dataMap.put(_v.id, _v);
        }
    }

    public java.util.Map<Integer, RewardItem> getDataMap() {
        return _dataMap;
    }

    public java.util.List<RewardItem> getDataList() {
        return _dataList;
    }

    public RewardItem get(int key) {
        return _dataMap.get(key);
    }

}

