
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

import com.google.gson.JsonElement;


public final class TbRewards {
    private final java.util.Map<Integer, Rewards> _dataMap;
    private final java.util.List<Rewards> _dataList;

    public TbRewards(JsonElement _buf) {
        _dataMap = new java.util.HashMap<Integer, Rewards>();
        _dataList = new java.util.ArrayList<>();

        for (JsonElement _e_ : _buf.getAsJsonArray()) {
            Rewards _v;
            _v = Rewards.deserialize(_e_.getAsJsonObject());
            _dataList.add(_v);
            _dataMap.put(_v.id, _v);
        }
    }

    public java.util.Map<Integer, Rewards> getDataMap() {
        return _dataMap;
    }

    public java.util.List<Rewards> getDataList() {
        return _dataList;
    }

    public Rewards get(int key) {
        return _dataMap.get(key);
    }

}

