
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

import com.google.gson.JsonElement;


public final class TbShop {
    private final java.util.Map<Integer, Shop> _dataMap;
    private final java.util.List<Shop> _dataList;

    public TbShop(JsonElement _buf) {
        _dataMap = new java.util.HashMap<Integer, Shop>();
        _dataList = new java.util.ArrayList<Shop>();

        for (JsonElement _e_ : _buf.getAsJsonArray()) {
            Shop _v;
            _v = Shop.deserialize(_e_.getAsJsonObject());
            _dataList.add(_v);
            _dataMap.put(_v.id, _v);
        }
    }

    public java.util.Map<Integer, Shop> getDataMap() {
        return _dataMap;
    }

    public java.util.List<Shop> getDataList() {
        return _dataList;
    }

    public Shop get(int key) {
        return _dataMap.get(key);
    }

}

