
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

import com.google.gson.JsonElement;


public final class TbSign {
    private final java.util.Map<Integer, Sign> _dataMap;
    private final java.util.List<Sign> _dataList;

    public TbSign(JsonElement _buf) {
        _dataMap = new java.util.HashMap<Integer, Sign>();
        _dataList = new java.util.ArrayList<Sign>();

        for (JsonElement _e_ : _buf.getAsJsonArray()) {
            Sign _v;
            _v = Sign.deserialize(_e_.getAsJsonObject());
            _dataList.add(_v);
            _dataMap.put(_v.id, _v);
        }
    }

    public java.util.Map<Integer, Sign> getDataMap() {
        return _dataMap;
    }

    public java.util.List<Sign> getDataList() {
        return _dataList;
    }

    public Sign get(int key) {
        return _dataMap.get(key);
    }

}

