
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

import com.google.gson.JsonElement;


public final class TbWarOrder {
    private final java.util.Map<Integer, WarOrder> _dataMap;
    private final java.util.List<WarOrder> _dataList;

    public TbWarOrder(JsonElement _buf) {
        _dataMap = new java.util.HashMap<Integer, WarOrder>();
        _dataList = new java.util.ArrayList<WarOrder>();

        for (JsonElement _e_ : _buf.getAsJsonArray()) {
            WarOrder _v;
            _v = WarOrder.deserialize(_e_.getAsJsonObject());
            _dataList.add(_v);
            _dataMap.put(_v.id, _v);
        }
    }

    public java.util.Map<Integer, WarOrder> getDataMap() {
        return _dataMap;
    }

    public java.util.List<WarOrder> getDataList() {
        return _dataList;
    }

    public WarOrder get(int key) {
        return _dataMap.get(key);
    }

}

