
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

import com.google.gson.JsonElement;


public final class TbWinning {
    private final java.util.Map<Integer, Winning> _dataMap;
    private final java.util.List<Winning> _dataList;

    public TbWinning(JsonElement _buf) {
        _dataMap = new java.util.HashMap<Integer, Winning>();
        _dataList = new java.util.ArrayList<Winning>();

        for (JsonElement _e_ : _buf.getAsJsonArray()) {
            Winning _v;
            _v = Winning.deserialize(_e_.getAsJsonObject());
            _dataList.add(_v);
            _dataMap.put(_v.id, _v);
        }
    }

    public java.util.Map<Integer, Winning> getDataMap() {
        return _dataMap;
    }

    public java.util.List<Winning> getDataList() {
        return _dataList;
    }

    public Winning get(int key) {
        return _dataMap.get(key);
    }

}

