
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

import com.google.gson.JsonObject;
import luban.AbstractBean;


public final class WarOrder extends AbstractBean {
    public static final int __ID__ = 534364518;
    /**
     * 这是id
     */
    public final int id;
    /**
     * 0全平台<br/>1微信<br/>2抖音
     */
    public final int plamform;
    /**
     * 类型
     */
    public final int type;
    /**
     * 等级类型
     */
    public final int levelType;
    /**
     * 等级
     */
    public final int level;
    /**
     * 战令每级所需经验
     */
    public final int levelExp;
    /**
     * 总经验
     */
    public final int totalExp;
    /**
     * 名字
     */
    public final String name;
    /**
     * 领取次数
     */
    public final int times;
    /**
     * 道具
     */
    public final int items;
    /**
     * 数量
     */
    public final int number;
    public WarOrder(JsonObject _buf) {
        id = _buf.get("id").getAsInt();
        plamform = _buf.get("plamform").getAsInt();
        type = _buf.get("type").getAsInt();
        levelType = _buf.get("levelType").getAsInt();
        level = _buf.get("level").getAsInt();
        levelExp = _buf.get("levelExp").getAsInt();
        totalExp = _buf.get("totalExp").getAsInt();
        name = _buf.get("name").getAsString();
        times = _buf.get("times").getAsInt();
        items = _buf.get("items").getAsInt();
        number = _buf.get("number").getAsInt();
    }

    public static WarOrder deserialize(JsonObject _buf) {
        return new WarOrder(_buf);
    }

    @Override
    public int getTypeId() {
        return __ID__;
    }

    @Override
    public String toString() {
        return "{ "
                + "(format_field_name __code_style field.name):" + id + ","
                + "(format_field_name __code_style field.name):" + plamform + ","
                + "(format_field_name __code_style field.name):" + type + ","
                + "(format_field_name __code_style field.name):" + levelType + ","
                + "(format_field_name __code_style field.name):" + level + ","
                + "(format_field_name __code_style field.name):" + levelExp + ","
                + "(format_field_name __code_style field.name):" + totalExp + ","
                + "(format_field_name __code_style field.name):" + name + ","
                + "(format_field_name __code_style field.name):" + times + ","
                + "(format_field_name __code_style field.name):" + items + ","
                + "(format_field_name __code_style field.name):" + number + ","
                + "}";
    }
}

