
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

import com.google.gson.JsonObject;
import luban.AbstractBean;


public final class Winning extends AbstractBean {
    public static final int __ID__ = -1280528784;
    public final int id;
    /**
     * 连胜次数
     */
    public final int win;
    /**
     * 加成
     */
    public final int addition;
    public Winning(JsonObject _buf) {
        id = _buf.get("id").getAsInt();
        win = _buf.get("win").getAsInt();
        addition = _buf.get("addition").getAsInt();
    }

    public static Winning deserialize(JsonObject _buf) {
        return new Winning(_buf);
    }

    @Override
    public int getTypeId() {
        return __ID__;
    }

    @Override
    public String toString() {
        return "{ "
                + "(format_field_name __code_style field.name):" + id + ","
                + "(format_field_name __code_style field.name):" + win + ","
                + "(format_field_name __code_style field.name):" + addition + ","
                + "}";
    }
}

