
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

import luban.*;
import com.google.gson.JsonObject;


public final class Item extends AbstractBean {
	
	public Item(JsonObject _buf) { 
        id = _buf.get("id").getAsInt();
        type = _buf.get("type").getAsInt();
        name = _buf.get("name").getAsString();
        res = _buf.get("res").getAsString();
        max = _buf.get("max").getAsInt();
        desc = _buf.get("desc").getAsString();
    }

    public static Item deserialize(JsonObject _buf) {
            return new Item(_buf);
    }

    /**
     * 这是id
     */
    public final int id;
    /**
     * 物品类型
     */
    public final int type;
    /**
     * 名字
     */
    public final String name;
    public final String res;
    /**
     * 上限
     */
    public final int max;
    /**
     * 描述
     */
    public final String desc;

    public static final int __ID__ = 2289459;
    
    @Override
    public int getTypeId() { return __ID__; }

    @Override
    public String toString() {
        return "{ "
        + "id:" + id + ","
        + "type:" + type + ","
        + "name:" + name + ","
        + "res:" + res + ","
        + "max:" + max + ","
        + "desc:" + desc + ","
        + "}";
    }
}

