
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;

import com.think.luban.anno.TableRepository;
import com.think.luban.repository.CfgRepository;

@TableRepository(id = "id", file = "tbitem")
public interface TbItem extends CfgRepository<Item, Integer> {
    
}
