package com.think.luban;


//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

import cfg.TbCommonConfig;
import cfg.TbDrop;
import cfg.TbFish;
import cfg.TbGameLevel;
import cfg.TbGuideCard;
import cfg.TbItem;
import cfg.TbLevel;
import cfg.TbRewardGroup;
import cfg.TbRewardItem;
import cfg.TbRewards;
import cfg.TbShop;
import cfg.TbSign;
import cfg.TbWarOrder;
import cfg.TbWinning;
import com.google.gson.JsonElement;
import com.think.luban.loader.ITableLoader;

public final class Tables {

    private final ITableLoader<JsonElement> _loader;
    private TbGameLevel _tbgamelevel;
    private TbFish _tbfish;
    private TbRewards _tbrewards;
    private TbRewardGroup _tbrewardgroup;
    private TbRewardItem _tbrewarditem;
    private TbItem _tbitem;
    private TbShop _tbshop;
    private TbLevel _tblevel;
    private TbWarOrder _tbwarorder;
    private TbGuideCard _tbguidecard;
    private TbSign _tbsign;
    private TbCommonConfig _tbcommonconfig;
    private TbWinning _tbwinning;
    private TbDrop _tbdrop;

    public Tables(ITableLoader<?> loader) {
        this._loader = (ITableLoader<JsonElement>) loader;
    }

    public TbGameLevel getTbGameLevel() {
        return _tbgamelevel;
    }

    public TbFish getTbFish() {
        return _tbfish;
    }

    public TbRewards getTbRewards() {
        return _tbrewards;
    }

    public TbRewardGroup getTbRewardGroup() {
        return _tbrewardgroup;
    }

    public TbRewardItem getTbRewardItem() {
        return _tbrewarditem;
    }

    public TbItem getTbItem() {
        return _tbitem;
    }

    public TbShop getTbShop() {
        return _tbshop;
    }

    public TbLevel getTbLevel() {
        return _tblevel;
    }

    public TbWarOrder getTbWarOrder() {
        return _tbwarorder;
    }

    public TbGuideCard getTbGuideCard() {
        return _tbguidecard;
    }

    public TbSign getTbSign() {
        return _tbsign;
    }

    public TbCommonConfig getTbCommonConfig() {
        return _tbcommonconfig;
    }

    public TbWinning getTbWinning() {
        return _tbwinning;
    }

    public TbDrop getTbDrop() {
        return _tbdrop;
    }

    public void reload(IJsonLoader loader) throws java.io.IOException {
        _tbgamelevel = new TbGameLevel(loader.load("tbgamelevel"));
        _tbfish = new TbFish(loader.load("tbfish"));
        _tbrewards = new TbRewards(loader.load("tbrewards"));
        _tbrewardgroup = new TbRewardGroup(loader.load("tbrewardgroup"));
        _tbrewarditem = new TbRewardItem(loader.load("tbrewarditem"));
        _tbitem = new TbItem(loader.load("tbitem"));
        _tbshop = new TbShop(loader.load("tbshop"));
        _tblevel = new TbLevel(loader.load("tblevel"));
        _tbwarorder = new TbWarOrder(loader.load("tbwarorder"));
        _tbguidecard = new TbGuideCard(loader.load("tbguidecard"));
        _tbsign = new TbSign(loader.load("tbsign"));
        _tbcommonconfig = new TbCommonConfig(loader.load("tbcommonconfig"));
        _tbwinning = new TbWinning(loader.load("tbwinning"));
        _tbdrop = new TbDrop(loader.load("tbdrop"));
    }

    public interface IJsonLoader {
        JsonElement load(String file) throws java.io.IOException;
    }
}


