
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg.item;

import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import luban.*;


public final class Drop extends AbstractBean {
    public static final int __ID__ = 2107135242;
    public final int Id;
    /**
     * 权重
     */
    public final int weight;
    /**
     * 分组
     */
    public final java.util.ArrayList<Integer> group;
    /**
     * 数量
     */
    public final int count;
    /**
     * 最大数量，有值，商城里就需要随机
     */
    public final int countMax;
    public final int countStep;
    public Drop(JsonObject _buf) {
        Id = _buf.get("Id").getAsInt();
        weight = _buf.get("weight").getAsInt();
        {
            com.google.gson.JsonArray _json0_ = _buf.get("group").getAsJsonArray();
            group = new java.util.ArrayList<Integer>(_json0_.size());
            for (JsonElement _e0 : _json0_) {
                int _v0;
                _v0 = _e0.getAsInt();
                group.add(_v0);
            }
        }
        count = _buf.get("count").getAsInt();
        countMax = _buf.get("countMax").getAsInt();
        countStep = _buf.get("countStep").getAsInt();
    }

    public static Drop deserialize(JsonObject _buf) {
        return new Drop(_buf);
    }

    @Override
    public int getTypeId() {
        return __ID__;
    }

    @Override
    public String toString() {
        return "{ "
                + "(format_field_name __code_style field.name):" + Id + ","
                + "(format_field_name __code_style field.name):" + weight + ","
                + "(format_field_name __code_style field.name):" + group + ","
                + "(format_field_name __code_style field.name):" + count + ","
                + "(format_field_name __code_style field.name):" + countMax + ","
                + "(format_field_name __code_style field.name):" + countStep + ","
                + "}";
    }
}

