
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg.item;

import com.google.gson.JsonObject;
import luban.*;


public final class Reward1 extends AbstractBean {
    public static final int __ID__ = 1893988071;
    /**
     * id
     */
    public final int Id;
    /**
     * 数量
     */
    public final int count;
    public Reward1(JsonObject _buf) {
        Id = _buf.get("Id").getAsInt();
        count = _buf.get("count").getAsInt();
    }

    public static Reward1 deserialize(JsonObject _buf) {
        return new Reward1(_buf);
    }

    @Override
    public int getTypeId() {
        return __ID__;
    }

    @Override
    public String toString() {
        return "{ "
                + "(format_field_name __code_style field.name):" + Id + ","
                + "(format_field_name __code_style field.name):" + count + ","
                + "}";
    }
}

