
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg.item;

import com.google.gson.JsonObject;
import luban.*;


public final class Reward extends AbstractBean {
    public static final int __ID__ = -1878566262;
    public final int Id;
    /**
     * 数量
     */
    public final int count;
    /**
     * 最大数量，有值，商城里就需要随机
     */
    public final int countMax;
    public Reward(JsonObject _buf) {
        Id = _buf.get("Id").getAsInt();
        count = _buf.get("count").getAsInt();
        countMax = _buf.get("countMax").getAsInt();
    }

    public static Reward deserialize(JsonObject _buf) {
        return new Reward(_buf);
    }

    @Override
    public int getTypeId() {
        return __ID__;
    }

    @Override
    public String toString() {
        return "{ "
                + "(format_field_name __code_style field.name):" + Id + ","
                + "(format_field_name __code_style field.name):" + count + ","
                + "(format_field_name __code_style field.name):" + countMax + ","
                + "}";
    }
}

